PR: Issue 194
archivesunleashed/archivesunleashed.org pull request #196
Opened 2021-02-02 14:39 UTC by SamFritz

Takes care of content cohort page + home page with link to cohort page

Issue 194: https://github.com/archivesunleashed/archivesunleashed.org/issues/195

2021-02-02 15:36 UTC, ianmilligan1 requested changes
First pass - this looks great! Thanks @SamFritz. Some relatively minor suggestions here.

2021-02-02 15:36 UTC, ianmilligan1 commented on content/_index.md
> +Supported by a new grant by [The Andrew W. Mellon Foundation](https://mellon.org/), Archives Unleashed is partnering with our colleagues at the [Internet Archive](https://archive.org). We will be int
I suppose we can drop "new grant" at this period (how time flies)

Maybe just "Supported by [The Andrew W. Mellon Foundation](https://mellon.org/), Archives Unleashed is..."

2021-02-02 15:36 UTC, ianmilligan1 commented on content/_index.md
> +Supported by a new grant by [The Andrew W. Mellon Foundation](https://mellon.org/), Archives Unleashed is partnering with our colleagues at the [Internet Archive](https://archive.org). We will be int
also should add a "the" before "Archive-It service"

2021-02-02 15:36 UTC, ianmilligan1 commented on content/_index.md
> +![funding agencies](/images/logo-AU-funding.png)
Fancy!

2021-02-02 15:36 UTC, ianmilligan1 commented on content/cohorts/index.md
> +We are looking to select **five cohorts** in the July 2021 to June 2022 period who will receive the following support:
let's put "up to" five cohorts (classic hedging of bets)

2021-02-02 15:36 UTC, ianmilligan1 commented on content/cohorts/index.md
> +	* Opening event: virtual [July 2021]
Let's specify that it's virtual due to COVID-19

2021-02-02 15:36 UTC, ianmilligan1 commented on content/cohorts/index.md
> +	* Closing event: Internet Archive, San Francisco, California, United States [May 2022]
Can we put some tentative language in there, i.e. Tentatively May 2022

Tentative in that things could shift due to logistics, _and/or_ public health measures. Knock on wood not the latter.

2021-02-02 15:36 UTC, ianmilligan1 commented on content/cohorts/index.md
> +* **Bi-weekly mentorship** and support meetings with the Archives Unleashed team;
I always get confused with 'bi-weekly' as it seems to have two different meanings!

Let's bring mentorship/support meetings together to `bi-monthly mentorship meetings`

2021-02-02 15:36 UTC, ianmilligan1 commented on content/cohorts/index.md
> +* **Funding** of $11,500 CAD in to support project work and travel to the closing event.
remove `and travel to the closing event` -> we can get separate support on closing event travel 👍 

so the $11,500 can be relatively unrestricted

2021-02-02 15:36 UTC, ianmilligan1 commented on content/cohorts/index.md
> +**The Cohorts**: can be disciplinary or interdisciplinary and should include no more than five individuals. Graduate students, postdoctoral fellows, and those in precarious or sessional positions are
can probably drop the `:` after The Cohorts

2021-02-02 15:36 UTC, ianmilligan1 commented on content/cohorts/index.md
> +Prepare you submission package using the **Cohort application**, to address the following areas:
I assume Cohort Application will link to the PDF?

2021-02-02 15:36 UTC, ianmilligan1 commented on content/cohorts/index.md
> +	* **Project Summary**: describe the research problem you aim to approach with web archives;
Should we put a word limit on this? Def. no more than 500 words. Maybe we can chat at the team meeting?

2021-02-02 15:36 UTC, ianmilligan1 commented on content/cohorts/index.md
> +	* **Timeline**: provide an brief overview of how you will conduct the project.
Def. no more than 250 words or so here.

2021-02-02 16:37 UTC, SamFritz commented on content/cohorts/index.md
> +* **Bi-weekly mentorship** and support meetings with the Archives Unleashed team;
ah yes! thank you!

2021-02-02 16:40 UTC, SamFritz commented on content/cohorts/index.md
> +Prepare you submission package using the **Cohort application**, to address the following areas:
Yep! I will add in PDF, once language is tweaked/fix the fill-in box descriptions

2021-02-02 16:42 UTC, SamFritz commented on content/cohorts/index.md
> +	* **Project Summary**: describe the research problem you aim to approach with web archives;
added to agenda. Also updated this to read (max. 500 words)....which can be changed after group chat.

2021-02-02 16:43 UTC, SamFritz commented on content/cohorts/index.md
> +	* **Timeline**: provide an brief overview of how you will conduct the project.
again, put place holder text at end of datasets/timeline to reach (max. 250 words)

2021-02-02 21:26 UTC, ianmilligan1 approved these changes
Looks great - we'll bring some of those little questions to the standup meeting on Thursday!

2021-02-05 19:40 UTC, SamFritz commented
Will be adding in a new section to address examples of scholarship for inspiration: 

- Trevor Owens + Grace Thomas:  [The invention and dissemination of the spacer gif: implications for the future of access and use of web archives](https://doi.org/10.1007/s42803-019-00006-8)
  - spacer.gif (Nick's [blog post](https://news.archivesunleashed.org/geocities-and-the-spacer-gif-6a0f70e7ad5d) about their project)
- Matt Weber's [Assessing Local Journalism: News Deserts, Journalism Divides, and the Determinants of the Robustness of Local News](https://dewitt.sanford.duke.edu/wp-content/uploads/2018/08/Assessing-Local-Journalism_100-Communities.pdf)
- Datathon Projects:
  - Team Wildfyer (Vancouver)
  - Team Kompromat (Washington)
  - Team DC Punk (Washington)
  - Team Composers (NY)

2021-02-05 20:26 UTC, ianmilligan1 requested changes
Looks great - just a few minor suggestions!

2021-02-05 20:26 UTC, ianmilligan1 commented on content/cohorts/index.md
> +* **Access to the Archive-It Research Cloud** to generate custom datasets; and
👍

2021-02-05 20:26 UTC, ianmilligan1 commented on content/cohorts/index.md
> +Need some ideas to inspire your Cohort project? We've listed a few recent scholarly works and projects to showcase the variety of ways web archives can be explored, used, and visualized.
"scholarly works and projects" -> maybe just "projects"?

2021-02-05 20:26 UTC, ianmilligan1 commented on content/cohorts/index.md
> +Need some ideas to inspire your Cohort project? We've listed a few recent scholarly works and projects to showcase the variety of ways web archives can be explored, used, and visualized.
Maybe "Cohort project" -> "Cohort proposal"

2021-02-05 20:26 UTC, ianmilligan1 commented on content/cohorts/index.md
> +* [Assessing Local Journalism: News Deserts, Journalism Divides, and the Determinants of the Robustness of Local News](https://dewitt.sanford.duke.edu/wp-content/uploads/2018/08/Assessing-Local-Journ
Maybe put periods after the author lists? (getting pedantic here I know!)

2021-02-05 20:26 UTC, ianmilligan1 commented on content/cohorts/index.md
> +* [GeoCities and the spacer.gif](https://news.archivesunleashed.org/geocities-and-the-spacer-gif-6a0f70e7ad5d) by Nick Ruest
Maybe combine line 70 and 71; noting that Nick's piece is a sort of response of building on that research using our tools?

2021-02-05 20:26 UTC, ianmilligan1 commented on content/cohorts/index.md
> +**The Data**: With our recently announce integration with Archive-It, data available for use will primarily be institution web archive collections in Archive-it (https://archive-it.org). Additional d
Second Archive-it should be capitalized (i.e. Archive-It)

2021-02-10 15:31 UTC, ianmilligan1 requested changes
Just two minor typos caught!

2021-02-10 15:31 UTC, ianmilligan1 commented on content/cohorts/index.md
> +* CV for each named applicant (max 2 pages each) and can be attached to the email or appended to the applicaiton PDF; and
Just see a typo on "application" here!

2021-02-10 15:31 UTC, ianmilligan1 commented on content/cohorts/index.md
> +* **Funding** of $11,500 CAD to support project work. Additional support will be provided for travel to the Internet Archives event.
Internet Archives -> Internet Archive (singular)

2021-02-10 16:44 UTC, SamFritz commented on content/cohorts/index.md
> +* CV for each named applicant (max 2 pages each) and can be attached to the email or appended to the applicaiton PDF; and
oh my goodness! thank you for this catch!

2021-02-12 19:15 UTC, merged