Updating cohort projects
archivesunleashed/archivesunleashed.org pull request #248
Opened 2023-06-28 15:19 UTC by SamFritz

This PR adds in link to cohort project summary report, and a section for each team on scholarly outputs + achievements (@ianmilligan1 please feel free to rename this title)

Also addresses [Website Updates #243](https://github.com/archivesunleashed/archivesunleashed.org/issues/243) and fixes some small errors and broken links throughout .org

2023-06-28 15:22 UTC, ianmilligan1 requested changes
Looks great! Just two minor changes from me!

2023-06-28 15:22 UTC, ianmilligan1 commented on content/cohorts2021-2022/index.md
> +* Journal article currently under peer review with the Canadian Journal of Communication.
Why don't we change this to "Paper under review" - just to avoid specifics in the case of peer review

2023-06-28 15:22 UTC, ianmilligan1 commented on content/cohorts2021-2022/index.md
> +**[The AU Cohort Project Summaries Report](/images/AUCohortProjects.pdf)**, provides a final overview of research projects, including the web archive collections analyzed, a description of tools and
Maybe change "AU" to "Archives Unleashed"

2023-06-29 16:56 UTC, SamFritz commented
@ianmilligan1, thanks so much for the suggestions above - I've made those changes!

I also introduced some fixes and modifications to our Publications and Get Involved page to reflect the closing of the project. Let me know if anything seems out of place

2023-06-30 14:31 UTC, merged